### Working directory ###
#Define the absolute path to the species directory containing the input files (see Readme)
species_dir: "/cluster/projects/nn8013k/results/testing/assembly_pipeline/Athalia_rosae/iyAthRosa1/" 

### Adapterfilt parameters ###
adapterfilt_install_dir: "/cluster/projects/nn8013k/opt/HiFiAdapterFilt"
adapterfilt_modules: ["GCC/11.2.0", "CMake/3.21.1-GCCcore-11.2.0"]
#adapterfilt_conda_env: "EBPNor_GenomeAssembly_profile/conda.hifiadapterfilt.yaml"
adapterfilt_threads: "16"

### KMC k-mer counting parameters ###
KMC_k: "32" #kmer-size
KMC_t: "10" #threads
KMC_m: "38" #max RAM (GB)
KMC_ci: "1" #kmer inclusion lower boundary
KMC_cx: "10000" #kmer inclusion upper boundary
KMC_cs: "10000" #kmer counter max value

### Genomescope parameters ###
#GS_conda_env: "EBPNor_GenomeAssembly_profile/conda.genomescope.yaml"
GS_ploidy_range: ["1", "2", "4"] #ploidy levels to check

### Smudgeplot parameters ###
#smudge_conda_env: "EBPNor_GenomeAssembly_profile/conda.smudgeplot.yaml"
smudge_ploidy: "2" #assumed ploidy level
smudge_mem: "60G" #memory requirements
smudge_module: "Python/3.7.2-GCCcore-8.2.0" #additional module to load when using low-memory mode
smudge_path: "/cluster/projects/nn8013k/opt/KMC" #KMC verion allowing low-mem smudge calculation (smudge_pairs)

### HifiAsm Assembly parameters ###
#hifiasm_conda_env: "EBPNor_GenomeAssembly_profile/conda.hifiasm.yaml"
hifiasm_threads: "10" #threads
hifiasm_mem_per_cpu: "15G"
hifiasm_cluster_time: "96:00:00"

### BUSCO parameters ###
#busco_conda_env: "EBPNor_GenomeAssembly_profile/conda.busco.yaml"
busco_db_dir: "/cluster/projects/nn8013k/opt/busco_dbs/lineages"
busco_lineage: "aves" #BUSCO lineage for analysis
busco_threads: "10" #threads
busco_mem: "8G" #memory requirements

### Meryl parameters ###
#meryl_conda_env: "EBPNor_GenomeAssembly_profile/conda.meryl.yaml"
meryl_threads: "10"
meryl_k: "31"
meryl_memory: "38g"

### Yahs parameters ###
#yahs_conda_env: "EBPNor_GenomeAssembly_profile/conda.yahs.yaml"
yahs_cluster_time: "72:00:00"
#yahs_install_path: "/cluster/projects/nn8013k/opt/yahs"
yahs_threads: "16"
