### Working directory ###
#Define the absolute path to the species directory containing the input files (see Readme)
input_dir: "/path/to/input/data"

### Adapterfilt parameters ###
adapterfilt_install_dir: "/cluster/projects/nn8013k/opt/HiFiAdapterFilt"
adapterfilt_threads: "16"

### KMC k-mer counting parameters ###
KMC_path: "/cluster/projects/nn8013k/opt/KMC"
KMC_k: "32" #kmer-size
KMC_t: "10" #threads
KMC_m: "38" #max RAM (GB)
KMC_ci: "1" #kmer inclusion lower boundary
KMC_cx: "10000" #kmer inclusion upper boundary
KMC_cs: "10000" #kmer counter max value

### Genomescope parameters ###
GS_ploidy_range: ["1", "2", "4"] #ploidy levels to check

### Smudgeplot parameters ###
smudge_ploidy: "2" #assumed ploidy level
smudge_mem: "60G" #memory requirements

### HifiAsm Assembly parameters ###
hifiasm_threads: "10" #threads
hifiasm_mem_per_cpu: "15G"
hifiasm_cluster_time: "96:00:00"

### BUSCO parameters ###
busco_db_dir: "/cluster/projects/nn8013k/opt/busco_dbs/lineages"
busco_lineage: "aves" #BUSCO lineage for analysis
busco_threads: "10" #threads
busco_mem: "8G" #memory requirements

### Meryl parameters ###
meryl_threads: "10"
meryl_k: "31"
meryl_memory: "38g"

### Yahs parameters ###
yahs_cluster_time: "72:00:00"
yahs_threads: "16"

### FCS parameters ###
fcs_path: "/cluster/projects/nn8013k/opt/fcs/dist"
fcs_threads: "10"
fcs_adaptor_image: "/cluster/projects/nn8013k/opt/fcs/fcs-adaptor.sif"
fcs_adaptor_time: "6:0:0"
fcs_adaptor_mem: "3G"
fcs_gx_time: "2:0:0"
fcs_gx_mem: "60G"
fcs_gx_partition: "bigmem"
fcs_gx_image: "/cluster/projects/nn8013k/opt/fcs/fcs-gx.sif"
fcs_gx_db: "/cluster/projects/nn8013k/opt/fcs/gxdb"
taxid: "76058"
