### Input data ###
#Define the absolute path to the PACBIO reads
pacbio: "/cluster/projects/nn8013k/results/species/Spinus_spinus/bSpiSpi1/genomic_data/pacbio/bSpiSpi1.hifi.fastq.gz"
#Define the absolute path to the HIC reads, both forward and reverse (hicF and hicR)
hicF: "/cluster/projects/nn8013k/results/species/Spinus_spinus/bSpiSpi1/genomic_data/hic/1-25-146-Spinus-spinus_S98_L004_R1_001.fastq.gz"
hicR: "/cluster/projects/nn8013k/results/species/Spinus_spinus/bSpiSpi1/genomic_data/hic/1-25-146-Spinus-spinus_S98_L004_R2_001.fastq.gz"
#Define the absolute path to Oxford Nanopore reads, if available. If not, leave the parameter as an empty string ("")
ont: ""

### Adapterfilt parameters ###
adapterfilt_install_dir: "/cluster/projects/nn8013k/opt/HiFiAdapterFilt"
adapterfilt_threads: "16"

### KMC k-mer counting parameters ###
KMC_path: "/cluster/projects/nn8013k/opt/KMC"
KMC_k: "32" #kmer-size
KMC_t: "10" #threads
KMC_m: "38" #max RAM (GB)
KMC_ci: "1" #kmer inclusion lower boundary
KMC_cx: "10000" #kmer inclusion upper boundary
KMC_cs: "10000" #kmer counter max value
KMC_time: "48:0:0"

### Genomescope parameters ###
GS_ploidy_range: ["1", "2", "4"] #ploidy levels to check

### Smudgeplot parameters ###
smudge_ploidy: "2" #assumed ploidy level
smudge_mem: "60G" #memory requirements
smudge_time: "48:0:0"

### HifiAsm Assembly parameters ###
hifiasm_threads: "10" #threads
hifiasm_mem_per_cpu: "15G"
hifiasm_cluster_time: "96:00:00"
hifiasm_partition: "normal"

### BUSCO parameters ###
busco_db_dir: "/cluster/projects/nn8013k/opt/busco_dbs/lineages"
busco_lineage: "aves" #BUSCO lineage for analysis
busco_threads: "10" #threads
busco_mem: "8G" #memory requirements

### Meryl parameters ###
meryl_threads: "10"
meryl_k: "31"
meryl_memory: "38g"

### Yahs parameters ###
yahs_cluster_time: "72:00:00"
yahs_threads: "16"

### Oatk parameters ###
oatk_dir: "/cluster/projects/nn8013k/opt/oatk"
oatk_db: "/cluster/projects/nn8013k/opt/OatkDB/v20230921"
oatk_lineage: "aves"
oatk_isPlant: False
oatk_k: "1001" #syncmer size
oatk_c: "150" #syncmer coverage threshold (+- 5-10 times nuclear coverage)
oatk_threads: "8"
oatk_mem: "10G"

### FCS parameters ###
fcs_path: "/cluster/projects/nn8013k/opt/fcs/dist"
fcs_threads: "10"
fcs_adaptor_image: "/cluster/projects/nn8013k/opt/fcs/fcs-adaptor.sif"
fcs_adaptor_time: "6:0:0"
fcs_adaptor_mem: "3G"
fcs_gx_time: "2:0:0"
fcs_gx_mem: "60G"
fcs_gx_partition: "bigmem"
fcs_gx_image: "/cluster/projects/nn8013k/opt/fcs/fcs-gx.sif"
fcs_gx_db: "/cluster/projects/nn8013k/opt/fcs/gxdb"
taxid: "76058"

### Curation parameters ###
curation_mapping_mem: "5G"
curation_mapping_threads: "16"
curation_install_dir: "/cluster/projects/nn8013k/opt/rapid-curation/rapid_hic_software/"
curation_telomere_rep: "TTAGGG"
curation_time: "48:0:0"
